### ISSUE TITLE
Firmware source code?

### ISSUE THREAD

**Issue by flarn2006** [microbit-foundation/microbit-reference-design#13]
Where is the source code for the firmware?

**Comment by jaustin** [comment]
@flarn2006 this is a really old issue, but I missed it at the time, and I think it's worth answering it here now anyway in case other people have the same questions.

For the KL26Z the firmware source is the DAPLink project from Arm: https://github.com/ARMmbed/DAPLink

For the nRF51822, you can use different firmware images, but the most common low-level layer is the microbit-dal https://lancaster-university.github.io/microbit-docs/

See https://tech.microbit.org/ for more info on the software/firmware.
