### ISSUE TITLE
possible pin out problems or are there  different pin outs per package

### ISSUE THREAD

**Issue by OwenBrotherwood** [microbit-foundation/microbit-reference-design#7]
Nordic nRF51822-QFAA-R rev 3 (http://tech.microbit.org/hardware/) 
contra
https://upverter.com/eda/#tool=schematic,designId=65697ed30d7e35d3
- see datasheet pdf
example: Vdd 14 (ref design) is i/o in pdf

![image](https://cloud.githubusercontent.com/assets/866122/21784055/398b1d40-d6ba-11e6-9969-f2efc08df0e2.png)

https://github.com/microbit-foundation/microbit-reference-design/blob/master/PDF/Schematic%20Print/Schematic%20Prints.PDF

---
Current reference is 
![image](https://cloud.githubusercontent.com/assets/866122/21786085/a19d18cc-d6c2-11e6-8785-760462f84a43.png)

https://www.nordicsemi.com/eng/content/download/13358/214991/file/nRF51822_PS%20v2.0.pdf

**Comment by OwenBrotherwood** [comment]
[![mega:bit nRF Module by acornway 65697ed30d7e35d3 - Upverter](https://upverter.com/acornway/65697ed30d7e35d3/megabit-nRF-Module/embed_img/14840072700000/)](https://upverter.com/acornway/65697ed30d7e35d3/megabit-nRF-Module/#/)

**Comment by OwenBrotherwood** [comment]
The modules schematic is finished with relation to nordic doc.
I try and complete another module and find out how to connect sheets to one pcb
https://upverter.com/acornway/65697ed30d7e35d3/megabit-nRF51822-QFAA-Module/

**Comment by rolandvs** [comment]
The VDD on pin 14 is wrong. The symbol is not correct.  The current reference is ok, Also check out/use the latest of the datasheets >=3.3...

**Comment by jaustin** [comment]
The pinout used in the reference design is relating to the Raytac module, not the nRF51 SoC itself. So the pinouts are different, yes. Happy for me to close this issue given that explanation?

**Comment by jaustin** [comment]
Closing this issue after creating #10 to track clarifying the problem

**Comment by OwenBrotherwood** [comment]
The ref design uses modules:
http://tech.microbit.org/hardware/reference-design/

Module Choice
Because the micro:bit uses every pin on the nRF51822, only modules that exposed all of the GPIO of the chip could be used. We have started with the Raytac MDBT40, which is available from outlets like Seedstudio, and commonly used on things like Adafruit BLE boards.

```
This design is fully open source, and we’re happy to accept pull requests for variants that use other modules, or improvements.

For your own projects, using a different module is as simple as wiring the right pins. The hardware page has a detailed pinmap. Likewise, contributions to this pinmap document for other popular modules are welcome.

There is a list of nRF51882 modules maintained by Nordic Semiconductor, from which you could choose any module that has all 31GPIOs broken out. If your design doesn’t use all of the pins on the edge connector and you are able to recompile your software for your custom design (for example using mbed) then you could choose a range of other modules.

```
https://www.nordicsemi.com/eng/Products/3rd-Party-Bluetooth-low-energy-Modules
