### ISSUE TITLE
MAG module, Freescale Semiconductor	MAG3110FCR1 in progress

### ISSUE THREAD

**Issue by OwenBrotherwood** [microbit-foundation/microbit-reference-design#9]
[![mega:bit MAG Module by acornway 2094df3e50dc4aa4 - Upverter](https://upverter.com/acornway/2094df3e50dc4aa4/megabit-MAG-Module/embed_img/14840319097870/)](https://upverter.com/acornway/2094df3e50dc4aa4/megabit-MAG-Module/#/)

![image](https://cloud.githubusercontent.com/assets/866122/21796877/e02ec650-d70b-11e6-9776-1e31fd6cbefe.png)

**Comment by jaustin** [comment]
@OwenBrotherwood can you explain more clearly what the issue you're describing here is please? I can't see what you're suggesting I'm afraid... I presume this is to do with upverter import of the RD?

**Comment by OwenBrotherwood** [comment]
yep: issue is general ensure that there is a base for all schematics/pcb for ref design.
The doc for creating is the two references, ref design plus another one.
I cherry pic from reference design
